server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_e067c267e056
    token: b8b6
    app-id: wx5a228ff69e28a91f
    app-secret: 0bea03aa1310bac050aae79dd8703928
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000157689374
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNzbw/dzIuOVFUJQNjnntmamoDrUCJJqxfTP2aONmZovddThyxr5cJY1JVTLLN9yKzzdw7m9LEYkFbtmaEXSBTnZUfA3ZcV5JQCJ6foh9/31EwkMhgPRdPCXyFptk9c4/4PzBMTNSSIrxB8U295FRpIDqNcfJoqyC61rhVjpDnU/c2pA6aktgQnFUDCyLYWJLaCX/hwwKo4bLJ45ElZVTZrBDlFLMLbKlW8ioqlYKcYaMGvSIMS9casvBAKR8Xstj7DQgLgqo5VebuAoooZHvx6ASH6cS9N7EihqUa7fhTWO7hkveHXpsE7x7swpB5WAX7Ne2palIz+Ix5D8ZAv/X5AgMBAAECggEAGf0lDI6s05GBZ7LU3rugsao2gQhb4fX0RoSecd9D+1bNDgdTME0QMatNNmBdJA1VYIdajFx9HTebMU2zXHu2HVkE/8mcJMUaQOkVvurmN2uoAQ4Hf7+3Nc/o3afYPx5cy+iO3NPG9D1WsK0cOCKhVjUvr7T3+6fAllePJ569RbjmwMhqjQnCIeJSA7CJDr0ZjyO+nN0MAAFp6kW2ieLlWKWCW6Fp61d/Kh8nXqz9hXANguqN8lV7pd8r4r5TQ0RVqZYx3hEvwU1JGpFIk5dCZamyJTJF10R3814iz0OAATciyhGNb7I862ZfnIVbNjqWqwNro0POE4ORoanCFEhGQQKBgQDoyimh87SWXq4ohx6f29X3o9qFaNIsksCmL9K3wBRapSUILT1IHv19TcS7jV1BMYEQaeSnGfvO7jV+IIY1+ZzXSwITFr5hDGYiuihi2bEYC4pxGsHpoZy/I8mQmLtM/tOMfWAcksjAd+JwjhkcZUuppW/DqHM/mCDjt4J6jAF5nQKBgQDiUsSPYBWXFKdnEg4FDOZTEaR4CnWSvnvO/ky1xgeg4qccetlZdD9Vjzr/E185jBy9FZr1iWf5eEAFTfeavxKjGPipWSReYV3QFdXZdBKaEM1vVMSHiqT94NrU/bvo7Ru3uo1xIGV0q2K0d4CBs5sea3x2Q01lSEXeSyj1J54dDQKBgDoFwbDDPLzKJqClZSW1NrS924arJM/FWE1T2DLCppAdX4iVNhQW3VnxG1sgFiFcxG2h50MbP99JEn44fxtO9x/Wa1L0tUkdPQvk2JIi7ngu0Df20mR4Ssh9lAz9dJnxXitDSMR2daE7gG5LjMi+GsjTGnNrNiagtXns0JHY+bklAoGAVZhcAqWiRLto/JBVgQ955JzdiRDbmp40EPsYY/77T5uo/BpyLWTLtz4uX94hu5AEJncPXiGTk0QpYlg0dvAgylJdaR7vpEpKwrIfaNh/WIlWSO7UTTbgY6ww1zEHanaSbxA9AjXwaQmQkRRJI8SbvAuGzOtzUATfd80RNna/U9kCgYEAmQpszakh9HPNCtYbWv4UsZlOko09iLLEii+kU0Y6Jfaz0svn5/y//b2lpZL0S5gnxmdOM0zqkD7pNcju6/ELEdOs7C7O8j8xXWKE2MF3kL9dbs2gCZzF8o6d291A1MNJ+zIFKJ0ZTc+gh6TOfkAkP00/bPoIYWuA1UlTLqH1HUI=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8/x6M3Zm2UusZHNw/S1VFkJpre3FTFP3OVEjpgQF/2KVWt/q09xFHAt4va0Yt0umpyt8BfqgTqfocbzghEz/8taOxzvxvGKjLhLlhva1PW5oz+DxjHUO16WN8FYNfNoPwXtMzdG4JWsOfLGq1Bcb2NqlRhBJROcUV0IuGGAhtm7gGCmnNZWOzbgprgRwCmszjPHP/QxiTslH5Hop7KoKLFaxppC9jaOxkCbAyqNSmsupfKHEKgYtgrLo5cP8xA4LNDXsT8Dr7QhFqYKisZmiRd4J9LTywRrG6wicg1+LH2jMu0wvsBzg9vcuiO1xQVheoiRDuB+mzR58TAyf4UzLTwIDAQAB
  notify_url: https://43.143.58.180/api/v1/alipay/alipay_notify_url
  return_url: https://front.xiaofuge.tech
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml